name: CI
on:
    pull_request:
    push:
        branches:
            - master
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.2', '7.3', '7.4']
                dependencies: ['lowest', 'highest']
        name: PHP ${{ matrix.php }} tests on deps=${{ matrix.dependencies }}

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: mongodb

            - uses: "ramsey/composer-install@v1"
              with:
                    dependency-versions: ${{ matrix.dependencies }}

            -  run: vendor/bin/phpunit
